helm:
  parameters:
  - name: app1.image.name
    value: gcr.io/ninja-project-338811/nginx
    forcestring: true
  - name: app1.image.tag
    value: mybranch-1278
    forcestring: true
  - name: app2.image.name
    value: gcr.io/ninja-project-338811/nginx
    forcestring: true
  - name: app2.image.tag
    value: mybranch-1278
    forcestring: true
  - name: app3.image.name
    value: gcr.io/ninja-project-338811/nginx
    forcestring: true
  - name: app3.image.tag
    value: mybranch-1278
    forcestring: true
  - name: app4.image.name
    value: gcr.io/ninja-project-338811/nginx
    forcestring: true
  - name: app4.image.tag
    value: mybranch-1278
    forcestring: true
