name: argocd triggered webhook
on:
  repository_dispatch:
    types: [argocd-event]
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
    - name: Set Application Name
      id: set_app_name
      run: echo "::set-output name=app_name::${{ github.event.client_payload['argocd-application-name'] }}"
    - name: Create new branch with timestamp
      run: |
        echo the application that triggered this was ${{ steps.set_app_name.outputs.app_name }}
